name: mobilecurling_lobby
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.0.0
  dio: ^5.4.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  shelf_cors_headers: ^0.1.5
  tiny_storage: ^1.0.4

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
  build_runner: any
  freezed: ^2.4.5
  json_serializable: ^6.7.1

